version: '3.8'

volumes:
  backend_node_modules: {}
  frontend_node_modules: {}

services:
  backend:
    build:
      context: ./meme_generator_backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./meme_generator_backend:/usr/src/app:cached
      - backend_node_modules:/usr/src/app/node_modules
    command: sh -c "npm run start:dev"
    ports:
      - "5000:3000"
    environment:
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}

  frontend:
    build:
      context: ./meme_generator_frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./meme_generator_frontend:/app:cached
      - frontend_node_modules:/app/node_modules
    command: npm start
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:3000
    depends_on:
      - backend
